baseURL = 'http://edencreeper.ml/'
languageCode = 'en-gb'
title = "edencreeper"
theme = 'ananke'

[params]
  github = "https://github.com/edencreeper"
  description = "eden's website, made with Hugo."
  background_color_class = "bg-black"
