baseURL = 'http://edencreeper.ml/'
languageCode = 'en-gb'
title = "eden's hugo site"
theme = 'ananke'

[params]
  github = "https://github.com/edencreeper"
  description = "eden's website"
  background_color_class = "bg-black"
